#!/usr/bin/env bash

# Get the absolute path of the logger script directory
LOGGER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

source "$LOGGER_DIR/print"

info() {
    print "$@" blue "[INFO] $1"
}

success() {
    print "$@" green bold "[SUCCESS] $1"
}

warning() {
    print "$@" yellow "[WARNING] $1"
}

error() {
    print "$@" red bold "[ERROR] $1"
}


