#!/usr/bin/env bash

# Constants
get_terminal_width() {
    stty size 2>/dev/null | cut -d' ' -f2 || echo 80
}

if [ -t 1 ]; then
    export MAX_WIDTH=$(( $(get_terminal_width) - 2 ))
else
    export MAX_WIDTH=78
fi

export TAB_WIDTH=20
export INDENT_WIDTH=2

# Print functions
print() {
  parse_print_args "$@"
  local color_code
  color_code=$(get_color_code "$PRINT_COLOR" "$PRINT_STYLE")

  if [ "$PRINT_TAB" -eq 1 ]; then
    printf -v PRINT_TEXT "%s%*s" "$PRINT_TEXT" $((TAB_WIDTH - ${#PRINT_TEXT})) ""
  fi

  if [ "$PRINT_INDENT" -eq 1 ]; then
    PRINT_TEXT="$(printf "%${INDENT_WIDTH}s" "")$PRINT_TEXT"
  fi

  if [ "$PRINT_NL" -eq 0 ]; then
    echo -en "${color_code}${PRINT_TEXT}${NC}"
  else
    echo -e "${color_code}${PRINT_TEXT}${NC}"
  fi
}

new_line() {
    echo
}

